### ISSUE TITLE
Consider getting rid of the global `StorePath` and `InitStorage` on every cmd

### ISSUE THREAD

**Issue by timaa2k** [jr0d/dcoscertstrap#5]
I believe this would make the code more modular. The `cmd` package could still tap into each `pkg` as before and we could more easily convert it from a CLI.

**Comment by jr0d** [comment]
@timaa2k What would you suggest the change be? Pass in storage path to InitStorage from each command?

**Comment by jr0d** [comment]
https://github.com/jr0d/dcoscertstrap/search?q=StorePath&unscoped_q=StorePath < not too many places.. I could push that concatenation operation onto the callers

**Comment by jr0d** [comment]
If you think it is important enough, I will let you submit a PR, otherwise I am fine leaving it as is.

**Comment by jr0d** [comment]
Per slack discussion, I am closing this issue.
