### ISSUE TITLE
generateSerialNumber is not properly initialized

### ISSUE THREAD

**Issue by mhrabovcin** [jr0d/dcoscertstrap#7]
The `generateSerialNumber` function that generates "random" serial number will generate always the same number on subsequent runs because the random number generator is not initialized.

https://github.com/jr0d/dcoscertstrap/blob/master/pkg/gen/cert.go#L47-L50

https://play.golang.org/p/REFAKTyxoIF

**Comment by jr0d** [comment]
oof, good catch. I lost my seed operation during a refactor.

**Comment by jr0d** [comment]
@mhrabovcin This function is using rand/crypto which uses getrandom() on linux systems. I believe the go playground has a limitation where /dev/urandom is not directly exposed to the playground sandbox, resulting in the same value on every run.
